import { BaseEntity, Entity, PrimaryGeneratedColumn, Column } from 'typeorm';
import { TaskStatus } from './task-status.enum';

// typeorm uses entitites which are translated to the tables.
// so we can perform different operation on entity and typeorm will reflect it in the tables

@Entity()
export class Task extends BaseEntity {
  // primary key column and should be autogenerated and incremented
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;
}
